# Generated by Django 4.2.4 on 2023-09-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_key', models.CharField(max_length=100, unique=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('other_information', models.TextField(blank=True)),
            ],
        ),
    ]
