# Generated by Django 4.2.4 on 2023-09-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_lieferung_versicherungsunternehmen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieferung',
            name='lieferung_art',
            field=models.CharField(choices=[('1', 'UPS'), ('2', 'DHL'), ('3', 'Lieferung'), ('4', 'Abholung')], max_length=1),
        ),
        migrations.AlterField(
            model_name='maske',
            name='ausatemventil',
            field=models.CharField(choices=[('8901', 'Respironics'), ('8902', 'Weinmann Sf'), ('8912', 'Schalldämpfer'), ('8922', 'F&P'), ('8923', 'F&P Aclaim FF'), ('1', 'sonstige')], max_length=4),
        ),
        migrations.AlterField(
            model_name='maske',
            name='gaensegurgeln',
            field=models.CharField(choices=[('8811', '13cm, 15'), ('8812', '13cm, 22'), ('8813', '15cm, 15, PV'), ('8814', '20cm, 15, PV'), ('8821', '20cm, 15'), ('8754', 'Silikonadapter'), ('1', 'sonstige')], max_length=4),
        ),
        migrations.AlterField(
            model_name='maske',
            name='konnektoren',
            field=models.CharField(choices=[('8721', '15 mm'), ('8722', '22 mm'), ('8723', 'Rückatemsperrung'), ('8752', 'Doppelnippel'), ('8702', 'Titrationsadapter'), ('1', 'sonstige')], max_length=4),
        ),
        migrations.AlterField(
            model_name='maske',
            name='tuben',
            field=models.FloatField(choices=[(1, 6), (2, 6.5), (3, 8)], max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='abdruck_ort',
            field=models.CharField(blank=True, choices=[('1', 'im Labor'), ('2', 'in der Klinik'), ('3', 'beim Patienten')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gesichtstyp',
            field=models.CharField(choices=[('1', 'pyknisch'), ('2', 'athletisch'), ('3', 'leptosom')], max_length=1),
        ),
    ]
