# Generated by Django 4.2.4 on 2023-10-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_lieferung_versicherungsunternehmen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='abdruck_ort',
            field=models.CharField(blank=True, choices=[('im Labor', 'im Labor'), ('in der Klinik', 'in der Klinik'), ('beim Patienten', 'beim Patienten')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gesichtstyp',
            field=models.CharField(choices=[('pyknisch', 'pyknisch'), ('athletisch', 'athletisch'), ('leptosom', 'leptosom')], default='pyknisch', max_length=14),
        ),
    ]
