# Generated by Django 4.2.4 on 2023-10-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_abdruck_ort_alter_patient_gesichtstyp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensitivepatientdata',
            options={'verbose_name': 'Sensitive Patient Data', 'verbose_name_plural': 'Sensitive Patient Data'},
        ),
        migrations.AlterField(
            model_name='sensitivepatientdata',
            name='geburtsdatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensitivepatientdata',
            name='gen_datum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensitivepatientdata',
            name='handy_nummer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensitivepatientdata',
            name='kv_datum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensitivepatientdata',
            name='kv_nummer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensitivepatientdata',
            name='nachname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensitivepatientdata',
            name='postleitzahl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensitivepatientdata',
            name='stadt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensitivepatientdata',
            name='strasse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensitivepatientdata',
            name='telefon_nummer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensitivepatientdata',
            name='verordner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensitivepatientdata',
            name='vo_datum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensitivepatientdata',
            name='vorname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
