# Generated by Django 4.2.4 on 2023-10-07 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_sensitivepatientdata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensitivepatientdata',
            name='versicherungsunternehmen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.versicherungsunternehmen'),
        ),
    ]
