# Generated by Django 4.2.4 on 2023-11-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patient_stl_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='schlaf_unterkiefer_mm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
