# Generated by Django 4.2.4 on 2023-12-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patient_schlaf_unterkiefer_mm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maske',
            old_name='gerätetyp',
            new_name='geraetetyp',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='größe',
            new_name='groeße',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='prothesenträger',
            new_name='prothesentraeger',
        ),
    ]
