# Generated by Django 4.2.4 on 2023-12-14 10:39

from django.db import migrations, models
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_rename_gerätetyp_maske_geraetetyp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=100, unique=True, validators=[patients.models.validate_no_whitespace]),
        ),
    ]
